version: '3.8'
services:
  # MySQL Database
  mysqldb:
    image: mysql:latest
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stationSki
    volumes:
      - db:/var/lib/mysql
  # Backend SpringBoot
  gestion-station-ski-backend:
    image: nourelhoudaguelmami/gestion_ski:latest
    container_name: docker-compose-spring-boot
    ports:
      - 8089:8089
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/stationSki?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db :
