version: '3.8'
services:
  # MySQL Database
  mysqldb:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stationSki
      MYSQL_USER: root
      MYSQL_PASSWORD:
    volumes:
      - db:/var/lib/mysql

  # Backend Spring Boot Application
  gestion-station-ski-backend:
    depends_on:
      - mysqldb
    image: khouloudorfi/gestion-station-ski:latest
    ports:
      - 8089:8089
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/stationSki?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db :